before_install:
- gem update --system 2.1.11
- gem --version
rvm: 1.8.7
bundler_args: ''
notifications:
  email:
  - johnpuskar@gmail.com
env:
- PUPPET_VERSION=3.3.1
- PUPPET_VERSION=3.2.3
- PUPPET_VERSION=2.7.23
- PUPPET_VERSION=2.7.21
- PUPPET_VERSION=2.7.17
